# Travis CI

language: java

sudo: false

jdk:
  - oraclejdk11
  - openjdk14
  - openjdk13
  - openjdk12
  - openjdk11
  - openjdk10
  - openjdk9
  - openjdk8

cache:
 directories:
   - $HOME/.m2

# EOF
