# Travis CI

language: java

sudo: false

jdk:
  - oraclejdk11
  - oraclejdk10
  - oraclejdk9
  - oraclejdk8
  - openjdk11
  - openjdk10
  - openjdk9
  - openjdk8
  - openjdk7

cache:
 directories:
   - $HOME/.m2

# EOF
